name: OnlyEshop
version: 1.0.0
main: me.itzmatick.onlyEshop.OnlyEshop
api-version: 1.21

commands:
  eshop:
    description: Opens eshop
    usage: /eshop

  reload:
    description: Reload plugin
    usage: /reload eshop
    permission: only.eshops.reload

permissions:
  only.eshop.reload:
    description: Reload plugin permissions
    default: op